import htmlPlugin from '@html-eslint/eslint-plugin';
import htmlParser from '@html-eslint/parser';

export default {
  name: 'htmlConfig',
  files: ['**/*.html'],
  plugins: { '@html-eslint': htmlPlugin },
  languageOptions: { parser: htmlParser },
  rules: {
    '@html-eslint/require-lang': 'error',
    '@html-eslint/require-img-alt': 'error',
    '@html-eslint/require-doctype': 'error',
    '@html-eslint/require-title': 'error',
    '@html-eslint/no-multiple-h1': 'error',
    '@html-eslint/no-extra-spacing-attrs': 'error',
    '@html-eslint/attrs-newline': 'error',
    '@html-eslint/element-newline': ['error', { inline: ['$inline'] }],
    '@html-eslint/no-duplicate-id': 'error',
    '@html-eslint/indent': 'error',
    '@html-eslint/require-li-container': 'error',
    '@html-eslint/quotes': 'error',
    '@html-eslint/no-obsolete-tags': 'error',
    '@html-eslint/require-closing-tags': 'error',
    '@html-eslint/no-duplicate-attrs': 'error',
    '@html-eslint/use-baseline': 'error',
    '@html-eslint/no-inline-styles': 'error',
    '@html-eslint/no-extra-spacing-text': 'error',
    '@html-eslint/no-skip-heading-levels': 'warn',
    '@html-eslint/id-naming-convention': 'warn',
    '@html-eslint/require-attrs': 'error',
    '@html-eslint/require-meta-description': 'error',
    '@html-eslint/require-frame-title': 'warn',
    '@html-eslint/no-non-scalable-viewport': 'warn',
    '@html-eslint/no-positive-tabindex': 'warn',
    '@html-eslint/require-meta-viewport': 'warn',
    '@html-eslint/require-meta-charset': 'error',
    '@html-eslint/no-target-blank': 'error',
    '@html-eslint/no-abstract-roles': 'warn',
    '@html-eslint/require-button-type': 'error',
    '@html-eslint/no-aria-hidden-body': 'warn',
    '@html-eslint/no-multiple-empty-lines': 'warn',
    '@html-eslint/no-accesskey-attrs': 'warn',
    '@html-eslint/no-restricted-attrs': 'error',
    '@html-eslint/no-trailing-spaces': 'warn',
    '@html-eslint/no-restricted-attr-values': 'error',
    '@html-eslint/no-script-style-type': 'error',
    '@html-eslint/no-heading-inside-button': 'warn',
    '@html-eslint/no-invalid-role': 'warn',
    '@html-eslint/no-nested-interactive': 'error',
    '@html-eslint/lowercase': 'warn',
    '@html-eslint/require-open-graph-protocol': 'error',
    '@html-eslint/require-form-method': 'warn',
    '@html-eslint/sort-attrs': 'warn',
    '@html-eslint/prefer-https': 'error',
    '@html-eslint/require-input-label': 'warn',
    '@html-eslint/max-element-depth': ['error', { max: 24 }],
    '@html-eslint/require-explicit-size': 'error',
    '@html-eslint/no-duplicate-class': 'error',
  },
};
