import nodePlugin from 'eslint-plugin-n';

export default {
  plugins: { n: nodePlugin },
  rules: {
    'n/callback-return': 'error',
    'n/no-callback-literal': 'error',
    'n/exports-style': 'error',
    'n/file-extension-in-import': ['error', 'always'],
    'n/global-require': 'error',
    'n/handle-callback-err': [
      'error',
      '^(e|.*(e|E)rr|.*(e|E)rror|.*(e|E)x|.*(e|E)xception)',
    ],
    'n/hashbang': ['error', {
      ignoreUnpublished: false,
      executableMap: {
        '.js': 'node',
        '.mjs': 'node',
        '.cjs': 'node',
        '.jsx': 'node',
        '.ts': 'node',
        '.mts': 'node',
        '.cts': 'node',
        '.tsx': 'node',
      },
    }],
    'n/no-deprecated-api': 'error',
    'n/no-exports-assign': 'error',
    'n/no-extraneous-import': 'error',
    'n/no-extraneous-require': 'error',
    'n/no-hide-core-modules': 'error',
    'n/no-missing-import': 'error',
    'n/no-missing-require': 'error',
    'n/no-mixed-requires': 'error',
    'n/no-new-require': 'error',
    'n/no-path-concat': 'error',
    'n/no-process-env': 'error',
    'n/no-process-exit': 'error',
    'n/no-restricted-import': 'off',
    'n/no-restricted-require': 'off',
    'n/no-sync': 'error',
    'n/no-unpublished-bin': 'error',
    'n/no-unpublished-import': 'off',
    'n/no-unpublished-require': 'off',
    'n/no-unsupported-features/es-builtins': 'error',
    'n/no-unsupported-features/es-syntax': 'error',
    'n/no-unsupported-features/node-builtins': 'error',
    'n/prefer-global/buffer': 'error',
    'n/prefer-global/console': 'error',
    'n/prefer-global/process': 'error',
    'n/prefer-global/text-decoder': 'error',
    'n/prefer-global/text-encoder': 'error',
    'n/prefer-global/url': 'error',
    'n/prefer-global/url-search-params': 'error',
    'n/prefer-node-protocol': 'error',
    'n/prefer-promises/dns': 'error',
    'n/prefer-promises/fs': 'error',
    'n/process-exit-as-throw': 'error',
    'n/shebang': 'error',
  },
};
